name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image & push it to Dockerhub
      run: |
        echo "${{ secrets.DOCKERPWD }}" | docker login -u "akramulislam" --password-stdin
        docker image build -t webmagic1/flaskapp:v1 .
        docker push webmagic1/flaskapp:v1
