name: ci docker image 

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        #name: Set up QEMU
        #uses: docker/setup-qemu-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          image: akramulislam/githubaction #repo of dockerhub
          file: ./Dockerfile  # Path to your Dockerfile
          push: true
          tags: |
             akramulislam/githubaction:v1 