name: Docker Image CI

on:
  push:
    branches: none # [ "main" ]
  pull_request:
    branches: none # [ "main" ]


jobs:


  build-container:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      working-directory: app
      run: docker build . --file Dockerfile --tag my-app-webmagic:$(date +%s)
