name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-python:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and Push Docker Image
      run: |
       echo "${{ secrets.DOCKER_ACCESS_TOKEN }}" | docker login docker.io -u akramulislam --password-stdin
       docker image build -t docker.io/akramulislam/user/app:latest .
       docker push docker.io/akramulislam/user/app:latest






