name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image & push it to Dockerhub
      run: |
        echo "${{ secrets.DOCKERPWD }}" | docker login -u "
        docker build . --file Dockerfile --tag my-image-name:$(date +%s)
